name: aec-arm # you probably want to 'snapcraft register <name>'
version: 'master' # just for humans, typically '1.2+git' or '1.3.2'
summary: converts expression to arm cortex M4 instruction code # 79 char long summary
description: |
    This utility tries to convert given input file consisting of expressions to
    arm cortes M4 instructions and generates autogen.s file which can be used in    keil simulator

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps: 
  aec-arm:
    #command: usr/bin/python $SNAP/lib/python2.7/site-packages/aec/arm_expression_compiler_nobat.py
    command: ./bin/aec_arm
    plugs:
      - home # to enable reading or creating files

parts:
  aec-arm:
    plugin: python
    python-version: python3
    python-packages: ['ply']
    source: https://github.com/SvrAdityaReddy/Arm_Expression_Compiler.git
    source-tag: master
